spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8084}/eureka/
  instance:
    hostname: ${DOMAIN_NAME}
    secure-port-enabled: true
    non-secure-port-enabled: false
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
    homePageUrl: https://${eureka.instance.hostname}/
  password: ${EUREKA_PASSWORD}
security:
  user:
    password: ${eureka.password}
authorization:
  token: ${TOKEN}
---
spring:
  profiles: local
eureka:
  instance:
    hostname: localhost
    secure-port-enabled: false
    non-secure-port-enabled: true
    nonSecurePort: 8082
    homePageUrl: http://${eureka.instance.hostname}:${eureka.instance.nonSecurePort}/
    password: password
